version: '3.8'

services:
  data_api:
    build:
        context: .
        dockerfile: data_api.Dockerfile
    volumes:
      - ./data_api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - data_db

  data_db:
    image: cockroachdb/cockroach:v21.2.4
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - "./data:/cockroach/cockroach-data"
    command: start-single-node --insecure
