version: '3.8'

services:
  data_api:
    build:
        context: .
        dockerfile: data_api.Dockerfile
    volumes:
      - ./data_api:/data_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
        - data_db

  data_db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
